right_arm_cartesian_impedance_controller:
    type: "franka_example_controllers/CartesianImpedanceExampleController"
    joints:
        - right_arm_joint1
        - right_arm_joint2
        - right_arm_joint3
        - right_arm_joint4
        - right_arm_joint5
        - right_arm_joint6
        - right_arm_joint7

left_arm_cartesian_impedance_controller:
    type: "franka_example_controllers/CartesianImpedanceExampleController"
    joints:
        - left_arm_joint1
        - left_arm_joint2
        - left_arm_joint3
        - left_arm_joint4
        - left_arm_joint5
        - left_arm_joint6
        - left_arm_joint7