left_panda_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.001  # Joint tolerance is kept fairly tight
  goal_position_tolerance: 0.001  # Increased to 1 cm
  goal_orientation_tolerance: 0.001  # Increased to 0.57 degrees

right_panda_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001  # Increased to 1 cm
  goal_orientation_tolerance: 0.001  # Increased to 0.57 degrees

# left_panda_arm:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   goal_joint_tolerance: 0.0001
#   goal_position_tolerance: 0.0001
#   goal_orientation_tolerance: 0.001

# right_panda_arm:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#   goal_joint_tolerance: 0.0001
#   goal_position_tolerance: 0.0001
#   goal_orientation_tolerance: 0.001

